# Generated by Django 4.1.6 on 2023-03-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_article_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('Grocery', 'Бакалея'), ('Beverages', 'Напитки'), ('Household chemicals', 'Бытовая химия'), ('Others', 'Разное')], default='Others', max_length=20, verbose_name='Категория')),
                ('description', models.TextField(max_length=3000, verbose_name='Текст')),
                ('pic', models.ImageField(blank=True, default='unregistered_user_ava.png', null=True, upload_to='product_pic', verbose_name='Картинка')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='удалено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Дата и время удаления')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='article',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
